language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
before_install:
  - sudo apt-get install python-dev
install:
  - pip install pycodestyle
before_script:
  - pycodestyle --max-line-length=200 --ignore=E402 */*.py
  - pip install -e .
script:
  - python -m rfc7539.test
